# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exemple.mp3"
Content-Type: audio/mpeg

< ./exemple.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/5b5c6b34-ac69-4fab-bd9d-d9e059d0ae04/transcription
Content-Type: application/json

{
    "prompt": "clean architecture, ddd"
}

###

# @name generate-ai-completetion
POST http://localhost:3333/ai/generate
Content-Type: application/json

{
    "videoId": ,
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrição do video informado a seguir: '''{transcription}'''",
}